<?php

namespace Database\Seeders;

use App\Models\Achievement;
use Illuminate\Database\Seeder;

class AchievementSeeder extends Seeder
{
    public function run(): void
    {
        $achievements = [
            // Booking Achievements
            [
                'name' => 'First Steps',
                'slug' => 'first-steps',
                'description' => 'Book your first lesson and begin your learning journey.',
                'icon' => 'calendar',
                'color' => '#3B82F6',
                'points' => 25,
                'type' => 'booking_count',
                'threshold' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Regular Student',
                'slug' => 'regular-student',
                'description' => 'Complete 5 bookings to become a regular student.',
                'icon' => 'repeat',
                'color' => '#8B5CF6',
                'points' => 50,
                'type' => 'booking_count',
                'threshold' => 5,
                'is_active' => true,
            ],
            [
                'name' => 'Booking Enthusiast',
                'slug' => 'booking-enthusiast',
                'description' => 'Complete 10 bookings. You\'re on fire!',
                'icon' => 'flame',
                'color' => '#F59E0B',
                'points' => 100,
                'type' => 'booking_count',
                'threshold' => 10,
                'is_active' => true,
            ],
            [
                'name' => 'Lesson Master',
                'slug' => 'lesson-master',
                'description' => 'Complete 25 bookings. True dedication!',
                'icon' => 'award',
                'color' => '#EF4444',
                'points' => 250,
                'type' => 'booking_count',
                'threshold' => 25,
                'is_active' => true,
            ],
            [
                'name' => 'Learning Legend',
                'slug' => 'learning-legend',
                'description' => 'Complete 50 bookings. You\'re a learning legend!',
                'icon' => 'crown',
                'color' => '#EC4899',
                'points' => 500,
                'type' => 'booking_count',
                'threshold' => 50,
                'is_active' => true,
            ],
            // Course Completion Achievements
            [
                'name' => 'Course Graduate',
                'slug' => 'course-graduate',
                'description' => 'Complete your first course.',
                'icon' => 'book-check',
                'color' => '#10B981',
                'points' => 50,
                'type' => 'course_completed',
                'threshold' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Course Collector',
                'slug' => 'course-collector',
                'description' => 'Complete 3 different courses.',
                'icon' => 'library',
                'color' => '#06B6D4',
                'points' => 150,
                'type' => 'course_completed',
                'threshold' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'Course Expert',
                'slug' => 'course-expert',
                'description' => 'Complete 5 courses. Impressive knowledge!',
                'icon' => 'brain',
                'color' => '#8B5CF6',
                'points' => 300,
                'type' => 'course_completed',
                'threshold' => 5,
                'is_active' => true,
            ],
            // Review Achievements
            [
                'name' => 'First Review',
                'slug' => 'first-review',
                'description' => 'Leave your first review for a teacher.',
                'icon' => 'message-circle',
                'color' => '#F59E0B',
                'points' => 25,
                'type' => 'review_given',
                'threshold' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Feedback Provider',
                'slug' => 'feedback-provider',
                'description' => 'Leave 5 reviews to help other students.',
                'icon' => 'thumbs-up',
                'color' => '#3B82F6',
                'points' => 75,
                'type' => 'review_given',
                'threshold' => 5,
                'is_active' => true,
            ],
            [
                'name' => 'Top Reviewer',
                'slug' => 'top-reviewer',
                'description' => 'Leave 10 reviews. Your feedback matters!',
                'icon' => 'star',
                'color' => '#EC4899',
                'points' => 150,
                'type' => 'review_given',
                'threshold' => 10,
                'is_active' => true,
            ],
            // Streak Achievements
            [
                'name' => 'Weekly Streak',
                'slug' => 'weekly-streak',
                'description' => 'Maintain a 7-day activity streak.',
                'icon' => 'calendar-check',
                'color' => '#10B981',
                'points' => 50,
                'type' => 'streak',
                'threshold' => 7,
                'is_active' => true,
            ],
            [
                'name' => 'Two Week Warrior',
                'slug' => 'two-week-warrior',
                'description' => 'Maintain a 14-day activity streak.',
                'icon' => 'fire',
                'color' => '#F59E0B',
                'points' => 100,
                'type' => 'streak',
                'threshold' => 14,
                'is_active' => true,
            ],
            [
                'name' => 'Monthly Master',
                'slug' => 'monthly-master',
                'description' => 'Maintain a 30-day activity streak. Incredible!',
                'icon' => 'trophy',
                'color' => '#EF4444',
                'points' => 250,
                'type' => 'streak',
                'threshold' => 30,
                'is_active' => true,
            ],
            // Points Achievements
            [
                'name' => 'Point Hunter',
                'slug' => 'point-hunter',
                'description' => 'Earn 500 total points.',
                'icon' => 'target',
                'color' => '#8B5CF6',
                'points' => 50,
                'type' => 'points_earned',
                'threshold' => 500,
                'is_active' => true,
            ],
            [
                'name' => 'Point Collector',
                'slug' => 'point-collector',
                'description' => 'Earn 1000 total points.',
                'icon' => 'coins',
                'color' => '#F59E0B',
                'points' => 100,
                'type' => 'points_earned',
                'threshold' => 1000,
                'is_active' => true,
            ],
            [
                'name' => 'Point Millionaire',
                'slug' => 'point-millionaire',
                'description' => 'Earn 2500 total points. You\'re rich in knowledge!',
                'icon' => 'gem',
                'color' => '#EC4899',
                'points' => 250,
                'type' => 'points_earned',
                'threshold' => 2500,
                'is_active' => true,
            ],
            // Teacher Achievements
            [
                'name' => 'First Teacher',
                'slug' => 'first-teacher',
                'description' => 'Book your first lesson with a teacher.',
                'icon' => 'user-check',
                'color' => '#3B82F6',
                'points' => 25,
                'type' => 'unique_teachers',
                'threshold' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Diverse Learner',
                'slug' => 'diverse-learner',
                'description' => 'Learn from 3 different teachers.',
                'icon' => 'users',
                'color' => '#10B981',
                'points' => 75,
                'type' => 'unique_teachers',
                'threshold' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'Teacher Explorer',
                'slug' => 'teacher-explorer',
                'description' => 'Learn from 5 different teachers.',
                'icon' => 'compass',
                'color' => '#F59E0B',
                'points' => 150,
                'type' => 'unique_teachers',
                'threshold' => 5,
                'is_active' => true,
            ],
        ];

        foreach ($achievements as $achievement) {
            Achievement::firstOrCreate(['slug' => $achievement['slug']], $achievement);
        }
    }
}
